name: check user

on:
  push:
    branches:
      bash-win11-ci
defaults:
  run:
    shell: cmd
jobs:

  e2e-tests:
    timeout-minutes: 90
    runs-on: [self-hosted, x64, win11]
    steps:
      - name: change user and check output
        continue-on-error: false
        run: |
          sc --help
