name: e2e tests on Windows

on:
  push:
    branches:
        win11-ci
defaults:
  run:
    shell: powershell
jobs:

  e2e-tests:
    timeout-minutes: 90
    runs-on: [self-hosted, x64, win11]
    env:
      HOME: C:/Users/tuctuc
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
        persist-credentials: false
      - name: Remove Rancher Desktop distros from WSL
        continue-on-error: true
        run: |
          whoami
          wsl --unregister rancher-desktop
          wsl --unregister rancher-desktop-data
      - name: Cleanup Test Environment
        continue-on-error: true
        run: Start-Process -FilePath "clean-test-env.ps1" -WorkingDirectory "$env:HOME/Scripts"
      - name: Install Scoop
        continue-on-error: true
        run: Start-Process -FilePath "install-scoop.ps1" -WorkingDirectory "C:\Scripts"
      - name: Install Project Dependencies
        continue-on-error: true
        run: |
          Start-Process -FilePath "install-project-dependencies.ps1" -WorkingDirectory "C:\Scripts"
      - name: Install node
        run: Start-Process -FilePath "install-node.ps1" -WorkingDirectory "C:\Scripts"
      - name: Setup node
        run: Start-Process -FilePath "setup-node.ps1" -WorkingDirectory "C:\Scripts"
      - name: Install node dependencies
        run: |
          Start-Process -FilePath "install-node-mod.ps1" -WorkingDirectory "C:\Scripts"
      - name: Run e2e Tests
        continue-on-error: false
        run: |
          Start-Process -FilePath "run-e2e-tests.ps1" -WorkingDirectory "C:\Scripts"
